services:
  
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - final-dev:/var/lib/postgresql/data
      - ./src/init-data:/docker-entrypoint-initdb.d
  web:
    image: node:lts-alpine
    user: '' #you can remove this if you are facing access issues when installing node packages
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=prod
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:

      - ./:/home/node/app
    command: 'npm run dev'
    restart: unless-stopped
volumes:
  final-dev: