services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - final:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: node dist/bundle.js
    restart: unless-stopped

volumes:
  final:
