services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - final-prod:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    image: node:lts-alpine
    user: 'node' #you can remove this if you are facing access issues when installing node packages
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm start'
    restart: unless-stopped
volumes:
  final-prod: